# Generated by Django 3.1.2 on 2020-12-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0002_auto_20201203_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressionpicture',
            name='week',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
