# Generated by Django 3.1.2 on 2020-12-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0003_progressionpicture_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressionpicture',
            name='chest_measurement',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='progressionpicture',
            name='waist_measurement',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='progressionpicture',
            name='weight',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
