# Generated by Django 3.1.2 on 2020-12-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20201201_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouts',
            old_name='reps',
            new_name='reps1',
        ),
        migrations.RenameField(
            model_name='workouts',
            old_name='sets',
            new_name='reps10',
        ),
        migrations.AddField(
            model_name='workouts',
            name='reps2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='reps3',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='reps4',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='reps5',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='reps6',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='reps7',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='reps8',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='reps9',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='sets1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='sets10',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='sets2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='sets3',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='sets4',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='sets5',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='sets6',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='sets7',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='sets8',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='workouts',
            name='sets9',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True),
        ),
    ]
